import { type MetadataRoute } from "next";

const baseUrl = "https://equitylens-ai.vercel.app";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    { url: `${baseUrl}/` },
    { url: `${baseUrl}/stocks` },
    { url: `${baseUrl}/stocks/nvda` },
    { url: `${baseUrl}/stocks/tsla` },
    { url: `${baseUrl}/stocks/aapl` },
    { url: `${baseUrl}/stocks/msft` },
    { url: `${baseUrl}/stocks/googl` },
    { url: `${baseUrl}/stocks/amzn` },
    { url: `${baseUrl}/stocks/meta` },
    { url: `${baseUrl}/stocks/avgo` },
    { url: `${baseUrl}/stocks/orcl` },
    { url: `${baseUrl}/stocks/nflx` },
    { url: `${baseUrl}/stocks/amd` },
    { url: `${baseUrl}/stocks/arm` },
    { url: `${baseUrl}/stocks/tsm` },
    { url: `${baseUrl}/stocks/asml` },
    { url: `${baseUrl}/stocks/qcom` },
    { url: `${baseUrl}/stocks/intc` },
    { url: `${baseUrl}/stocks/mu` },
    { url: `${baseUrl}/stocks/mrvl` },
    { url: `${baseUrl}/stocks/smci` },
    { url: `${baseUrl}/stocks/pltr` },
    { url: `${baseUrl}/stocks/baba` },
    { url: `${baseUrl}/stocks/pdd` },
    { url: `${baseUrl}/stocks/jd` },
    { url: `${baseUrl}/stocks/bidu` },
    { url: `${baseUrl}/stocks/nio` },
    { url: `${baseUrl}/stocks/li` },
    { url: `${baseUrl}/stocks/xpev` },
    { url: `${baseUrl}/stocks/bili` },
    { url: `${baseUrl}/stocks/tme` },
    { url: `${baseUrl}/stocks/zh` },
    { url: `${baseUrl}/stocks/jpm` },
    { url: `${baseUrl}/stocks/bac` },
    { url: `${baseUrl}/stocks/wfc` },
    { url: `${baseUrl}/stocks/gs` },
    { url: `${baseUrl}/stocks/ms` },
    { url: `${baseUrl}/stocks/v` },
    { url: `${baseUrl}/stocks/ma` },
    { url: `${baseUrl}/stocks/pypl` },
    { url: `${baseUrl}/stocks/coin` },
    { url: `${baseUrl}/stocks/hood` },
    { url: `${baseUrl}/stocks/cost` },
    { url: `${baseUrl}/stocks/wmt` },
    { url: `${baseUrl}/stocks/mcd` },
    { url: `${baseUrl}/stocks/sbux` },
    { url: `${baseUrl}/stocks/ko` },
    { url: `${baseUrl}/stocks/pep` },
    { url: `${baseUrl}/stocks/nke` },
    { url: `${baseUrl}/stocks/dis` },
    { url: `${baseUrl}/stocks/pg` },
    { url: `${baseUrl}/stocks/hd` },
    { url: `${baseUrl}/stocks-to-watch` },
    { url: `${baseUrl}/earnings` },
    { url: `${baseUrl}/market-brief` },
    { url: `${baseUrl}/pricing` },
    { url: `${baseUrl}/about` },
    { url: `${baseUrl}/lists/ai-stocks-to-watch` },
    { url: `${baseUrl}/lists/semiconductor-stocks-to-watch` },
    { url: `${baseUrl}/lists/chinese-adr-stocks-to-watch` },
    { url: `${baseUrl}/lists/ev-stocks-to-watch` },
    { url: `${baseUrl}/lists/energy-stocks-to-watch` },
    { url: `${baseUrl}/privacy` },
    { url: `${baseUrl}/terms` },
    { url: `${baseUrl}/education` },
    { url: `${baseUrl}/education/how-to-analyze-a-stock` },
    { url: `${baseUrl}/education/how-to-read-an-earnings-report` },
    { url: `${baseUrl}/education/what-is-pe-ratio` },
    { url: `${baseUrl}/education/what-is-market-cap` },
    { url: `${baseUrl}/education/what-is-risk-analysis` },
  ];
}
